# DigitalOcean App Platform configuration
name: whitepointer-app
services:
- name: web
  source_dir: /
  github:
    repo: your-username/your-repo-name
    branch: main
  run_command: npm start
  build_command: npm ci && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /api/health
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_PATH
    value: /app/data/pbike-rescue.db